version: "3.9"

services:
  web-service:
    build:
      context: .
      args:
        - region=us-east-1
        - alice=0
      environment:
        # you can also define this variable on the machine environment from terminal (eg. export runtime_env=dev)
        -runtime_env=dev
  database:
    image: "mysql"
    env_file: 
